// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TermsColumns holds the columns for the "terms" table.
	TermsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// TermsTable holds the schema information for the "terms" table.
	TermsTable = &schema.Table{
		Name:       "terms",
		Columns:    TermsColumns,
		PrimaryKey: []*schema.Column{TermsColumns[0]},
	}
	// TermPointersColumns holds the columns for the "term_pointers" table.
	TermPointersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "term_id", Type: field.TypeInt, Nullable: true},
		{Name: "revision_id", Type: field.TypeInt, Nullable: true},
	}
	// TermPointersTable holds the schema information for the "term_pointers" table.
	TermPointersTable = &schema.Table{
		Name:       "term_pointers",
		Columns:    TermPointersColumns,
		PrimaryKey: []*schema.Column{TermPointersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "term_pointers_terms_pointers",
				Columns:    []*schema.Column{TermPointersColumns[1]},
				RefColumns: []*schema.Column{TermsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "term_pointers_term_revisions_pointers",
				Columns:    []*schema.Column{TermPointersColumns[2]},
				RefColumns: []*schema.Column{TermRevisionsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// TermRelatedsColumns holds the columns for the "term_relateds" table.
	TermRelatedsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "term_subject_id", Type: field.TypeInt, Nullable: true},
		{Name: "term_related_id", Type: field.TypeInt, Nullable: true},
	}
	// TermRelatedsTable holds the schema information for the "term_relateds" table.
	TermRelatedsTable = &schema.Table{
		Name:       "term_relateds",
		Columns:    TermRelatedsColumns,
		PrimaryKey: []*schema.Column{TermRelatedsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "term_relateds_terms_subject_id",
				Columns:    []*schema.Column{TermRelatedsColumns[1]},
				RefColumns: []*schema.Column{TermsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "term_relateds_terms_related_id",
				Columns:    []*schema.Column{TermRelatedsColumns[2]},
				RefColumns: []*schema.Column{TermsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// TermRevisionsColumns holds the columns for the "term_revisions" table.
	TermRevisionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "term_id", Type: field.TypeInt, Nullable: true},
	}
	// TermRevisionsTable holds the schema information for the "term_revisions" table.
	TermRevisionsTable = &schema.Table{
		Name:       "term_revisions",
		Columns:    TermRevisionsColumns,
		PrimaryKey: []*schema.Column{TermRevisionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "term_revisions_terms_revisions",
				Columns:    []*schema.Column{TermRevisionsColumns[4]},
				RefColumns: []*schema.Column{TermsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TermsTable,
		TermPointersTable,
		TermRelatedsTable,
		TermRevisionsTable,
	}
)

func init() {
	TermPointersTable.ForeignKeys[0].RefTable = TermsTable
	TermPointersTable.ForeignKeys[1].RefTable = TermRevisionsTable
	TermRelatedsTable.ForeignKeys[0].RefTable = TermsTable
	TermRelatedsTable.ForeignKeys[1].RefTable = TermsTable
	TermRevisionsTable.ForeignKeys[0].RefTable = TermsTable
}
