// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"devwiki/ent/predicate"
	"devwiki/ent/term"
	"devwiki/ent/termpointer"
	"devwiki/ent/termrelated"
	"devwiki/ent/termrevision"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeTerm         = "Term"
	TypeTermPointer  = "TermPointer"
	TypeTermRelated  = "TermRelated"
	TypeTermRevision = "TermRevision"
)

// TermMutation represents an operation that mutates the Term nodes in the graph.
type TermMutation struct {
	config
	op                Op
	typ               string
	id                *int
	name              *string
	created_at        *time.Time
	updated_at        *time.Time
	clearedFields     map[string]struct{}
	revisions         map[int]struct{}
	removedrevisions  map[int]struct{}
	clearedrevisions  bool
	pointers          map[int]struct{}
	removedpointers   map[int]struct{}
	clearedpointers   bool
	subject_id        map[int]struct{}
	removedsubject_id map[int]struct{}
	clearedsubject_id bool
	related_id        map[int]struct{}
	removedrelated_id map[int]struct{}
	clearedrelated_id bool
	done              bool
	oldValue          func(context.Context) (*Term, error)
	predicates        []predicate.Term
}

var _ ent.Mutation = (*TermMutation)(nil)

// termOption allows management of the mutation configuration using functional options.
type termOption func(*TermMutation)

// newTermMutation creates new mutation for the Term entity.
func newTermMutation(c config, op Op, opts ...termOption) *TermMutation {
	m := &TermMutation{
		config:        c,
		op:            op,
		typ:           TypeTerm,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withTermID sets the ID field of the mutation.
func withTermID(id int) termOption {
	return func(m *TermMutation) {
		var (
			err   error
			once  sync.Once
			value *Term
		)
		m.oldValue = func(ctx context.Context) (*Term, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Term.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withTerm sets the old Term of the mutation.
func withTerm(node *Term) termOption {
	return func(m *TermMutation) {
		m.oldValue = func(context.Context) (*Term, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m TermMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m TermMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *TermMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *TermMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Term.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetName sets the "name" field.
func (m *TermMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *TermMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the Term entity.
// If the Term object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TermMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *TermMutation) ResetName() {
	m.name = nil
}

// SetCreatedAt sets the "created_at" field.
func (m *TermMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *TermMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the Term entity.
// If the Term object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TermMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *TermMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *TermMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *TermMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the Term entity.
// If the Term object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TermMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *TermMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// AddRevisionIDs adds the "revisions" edge to the TermRevision entity by ids.
func (m *TermMutation) AddRevisionIDs(ids ...int) {
	if m.revisions == nil {
		m.revisions = make(map[int]struct{})
	}
	for i := range ids {
		m.revisions[ids[i]] = struct{}{}
	}
}

// ClearRevisions clears the "revisions" edge to the TermRevision entity.
func (m *TermMutation) ClearRevisions() {
	m.clearedrevisions = true
}

// RevisionsCleared reports if the "revisions" edge to the TermRevision entity was cleared.
func (m *TermMutation) RevisionsCleared() bool {
	return m.clearedrevisions
}

// RemoveRevisionIDs removes the "revisions" edge to the TermRevision entity by IDs.
func (m *TermMutation) RemoveRevisionIDs(ids ...int) {
	if m.removedrevisions == nil {
		m.removedrevisions = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.revisions, ids[i])
		m.removedrevisions[ids[i]] = struct{}{}
	}
}

// RemovedRevisions returns the removed IDs of the "revisions" edge to the TermRevision entity.
func (m *TermMutation) RemovedRevisionsIDs() (ids []int) {
	for id := range m.removedrevisions {
		ids = append(ids, id)
	}
	return
}

// RevisionsIDs returns the "revisions" edge IDs in the mutation.
func (m *TermMutation) RevisionsIDs() (ids []int) {
	for id := range m.revisions {
		ids = append(ids, id)
	}
	return
}

// ResetRevisions resets all changes to the "revisions" edge.
func (m *TermMutation) ResetRevisions() {
	m.revisions = nil
	m.clearedrevisions = false
	m.removedrevisions = nil
}

// AddPointerIDs adds the "pointers" edge to the TermPointer entity by ids.
func (m *TermMutation) AddPointerIDs(ids ...int) {
	if m.pointers == nil {
		m.pointers = make(map[int]struct{})
	}
	for i := range ids {
		m.pointers[ids[i]] = struct{}{}
	}
}

// ClearPointers clears the "pointers" edge to the TermPointer entity.
func (m *TermMutation) ClearPointers() {
	m.clearedpointers = true
}

// PointersCleared reports if the "pointers" edge to the TermPointer entity was cleared.
func (m *TermMutation) PointersCleared() bool {
	return m.clearedpointers
}

// RemovePointerIDs removes the "pointers" edge to the TermPointer entity by IDs.
func (m *TermMutation) RemovePointerIDs(ids ...int) {
	if m.removedpointers == nil {
		m.removedpointers = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.pointers, ids[i])
		m.removedpointers[ids[i]] = struct{}{}
	}
}

// RemovedPointers returns the removed IDs of the "pointers" edge to the TermPointer entity.
func (m *TermMutation) RemovedPointersIDs() (ids []int) {
	for id := range m.removedpointers {
		ids = append(ids, id)
	}
	return
}

// PointersIDs returns the "pointers" edge IDs in the mutation.
func (m *TermMutation) PointersIDs() (ids []int) {
	for id := range m.pointers {
		ids = append(ids, id)
	}
	return
}

// ResetPointers resets all changes to the "pointers" edge.
func (m *TermMutation) ResetPointers() {
	m.pointers = nil
	m.clearedpointers = false
	m.removedpointers = nil
}

// AddSubjectIDIDs adds the "subject_id" edge to the TermRelated entity by ids.
func (m *TermMutation) AddSubjectIDIDs(ids ...int) {
	if m.subject_id == nil {
		m.subject_id = make(map[int]struct{})
	}
	for i := range ids {
		m.subject_id[ids[i]] = struct{}{}
	}
}

// ClearSubjectID clears the "subject_id" edge to the TermRelated entity.
func (m *TermMutation) ClearSubjectID() {
	m.clearedsubject_id = true
}

// SubjectIDCleared reports if the "subject_id" edge to the TermRelated entity was cleared.
func (m *TermMutation) SubjectIDCleared() bool {
	return m.clearedsubject_id
}

// RemoveSubjectIDIDs removes the "subject_id" edge to the TermRelated entity by IDs.
func (m *TermMutation) RemoveSubjectIDIDs(ids ...int) {
	if m.removedsubject_id == nil {
		m.removedsubject_id = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.subject_id, ids[i])
		m.removedsubject_id[ids[i]] = struct{}{}
	}
}

// RemovedSubjectID returns the removed IDs of the "subject_id" edge to the TermRelated entity.
func (m *TermMutation) RemovedSubjectIDIDs() (ids []int) {
	for id := range m.removedsubject_id {
		ids = append(ids, id)
	}
	return
}

// SubjectIDIDs returns the "subject_id" edge IDs in the mutation.
func (m *TermMutation) SubjectIDIDs() (ids []int) {
	for id := range m.subject_id {
		ids = append(ids, id)
	}
	return
}

// ResetSubjectID resets all changes to the "subject_id" edge.
func (m *TermMutation) ResetSubjectID() {
	m.subject_id = nil
	m.clearedsubject_id = false
	m.removedsubject_id = nil
}

// AddRelatedIDIDs adds the "related_id" edge to the TermRelated entity by ids.
func (m *TermMutation) AddRelatedIDIDs(ids ...int) {
	if m.related_id == nil {
		m.related_id = make(map[int]struct{})
	}
	for i := range ids {
		m.related_id[ids[i]] = struct{}{}
	}
}

// ClearRelatedID clears the "related_id" edge to the TermRelated entity.
func (m *TermMutation) ClearRelatedID() {
	m.clearedrelated_id = true
}

// RelatedIDCleared reports if the "related_id" edge to the TermRelated entity was cleared.
func (m *TermMutation) RelatedIDCleared() bool {
	return m.clearedrelated_id
}

// RemoveRelatedIDIDs removes the "related_id" edge to the TermRelated entity by IDs.
func (m *TermMutation) RemoveRelatedIDIDs(ids ...int) {
	if m.removedrelated_id == nil {
		m.removedrelated_id = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.related_id, ids[i])
		m.removedrelated_id[ids[i]] = struct{}{}
	}
}

// RemovedRelatedID returns the removed IDs of the "related_id" edge to the TermRelated entity.
func (m *TermMutation) RemovedRelatedIDIDs() (ids []int) {
	for id := range m.removedrelated_id {
		ids = append(ids, id)
	}
	return
}

// RelatedIDIDs returns the "related_id" edge IDs in the mutation.
func (m *TermMutation) RelatedIDIDs() (ids []int) {
	for id := range m.related_id {
		ids = append(ids, id)
	}
	return
}

// ResetRelatedID resets all changes to the "related_id" edge.
func (m *TermMutation) ResetRelatedID() {
	m.related_id = nil
	m.clearedrelated_id = false
	m.removedrelated_id = nil
}

// Where appends a list predicates to the TermMutation builder.
func (m *TermMutation) Where(ps ...predicate.Term) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *TermMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (Term).
func (m *TermMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *TermMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.name != nil {
		fields = append(fields, term.FieldName)
	}
	if m.created_at != nil {
		fields = append(fields, term.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, term.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *TermMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case term.FieldName:
		return m.Name()
	case term.FieldCreatedAt:
		return m.CreatedAt()
	case term.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *TermMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case term.FieldName:
		return m.OldName(ctx)
	case term.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case term.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown Term field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TermMutation) SetField(name string, value ent.Value) error {
	switch name {
	case term.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case term.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case term.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown Term field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *TermMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *TermMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TermMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Term numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *TermMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *TermMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *TermMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Term nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *TermMutation) ResetField(name string) error {
	switch name {
	case term.FieldName:
		m.ResetName()
		return nil
	case term.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case term.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown Term field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *TermMutation) AddedEdges() []string {
	edges := make([]string, 0, 4)
	if m.revisions != nil {
		edges = append(edges, term.EdgeRevisions)
	}
	if m.pointers != nil {
		edges = append(edges, term.EdgePointers)
	}
	if m.subject_id != nil {
		edges = append(edges, term.EdgeSubjectID)
	}
	if m.related_id != nil {
		edges = append(edges, term.EdgeRelatedID)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *TermMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case term.EdgeRevisions:
		ids := make([]ent.Value, 0, len(m.revisions))
		for id := range m.revisions {
			ids = append(ids, id)
		}
		return ids
	case term.EdgePointers:
		ids := make([]ent.Value, 0, len(m.pointers))
		for id := range m.pointers {
			ids = append(ids, id)
		}
		return ids
	case term.EdgeSubjectID:
		ids := make([]ent.Value, 0, len(m.subject_id))
		for id := range m.subject_id {
			ids = append(ids, id)
		}
		return ids
	case term.EdgeRelatedID:
		ids := make([]ent.Value, 0, len(m.related_id))
		for id := range m.related_id {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *TermMutation) RemovedEdges() []string {
	edges := make([]string, 0, 4)
	if m.removedrevisions != nil {
		edges = append(edges, term.EdgeRevisions)
	}
	if m.removedpointers != nil {
		edges = append(edges, term.EdgePointers)
	}
	if m.removedsubject_id != nil {
		edges = append(edges, term.EdgeSubjectID)
	}
	if m.removedrelated_id != nil {
		edges = append(edges, term.EdgeRelatedID)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *TermMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case term.EdgeRevisions:
		ids := make([]ent.Value, 0, len(m.removedrevisions))
		for id := range m.removedrevisions {
			ids = append(ids, id)
		}
		return ids
	case term.EdgePointers:
		ids := make([]ent.Value, 0, len(m.removedpointers))
		for id := range m.removedpointers {
			ids = append(ids, id)
		}
		return ids
	case term.EdgeSubjectID:
		ids := make([]ent.Value, 0, len(m.removedsubject_id))
		for id := range m.removedsubject_id {
			ids = append(ids, id)
		}
		return ids
	case term.EdgeRelatedID:
		ids := make([]ent.Value, 0, len(m.removedrelated_id))
		for id := range m.removedrelated_id {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *TermMutation) ClearedEdges() []string {
	edges := make([]string, 0, 4)
	if m.clearedrevisions {
		edges = append(edges, term.EdgeRevisions)
	}
	if m.clearedpointers {
		edges = append(edges, term.EdgePointers)
	}
	if m.clearedsubject_id {
		edges = append(edges, term.EdgeSubjectID)
	}
	if m.clearedrelated_id {
		edges = append(edges, term.EdgeRelatedID)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *TermMutation) EdgeCleared(name string) bool {
	switch name {
	case term.EdgeRevisions:
		return m.clearedrevisions
	case term.EdgePointers:
		return m.clearedpointers
	case term.EdgeSubjectID:
		return m.clearedsubject_id
	case term.EdgeRelatedID:
		return m.clearedrelated_id
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *TermMutation) ClearEdge(name string) error {
	switch name {
	}
	return fmt.Errorf("unknown Term unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *TermMutation) ResetEdge(name string) error {
	switch name {
	case term.EdgeRevisions:
		m.ResetRevisions()
		return nil
	case term.EdgePointers:
		m.ResetPointers()
		return nil
	case term.EdgeSubjectID:
		m.ResetSubjectID()
		return nil
	case term.EdgeRelatedID:
		m.ResetRelatedID()
		return nil
	}
	return fmt.Errorf("unknown Term edge %s", name)
}

// TermPointerMutation represents an operation that mutates the TermPointer nodes in the graph.
type TermPointerMutation struct {
	config
	op              Op
	typ             string
	id              *int
	clearedFields   map[string]struct{}
	term            *int
	clearedterm     bool
	revision        *int
	clearedrevision bool
	done            bool
	oldValue        func(context.Context) (*TermPointer, error)
	predicates      []predicate.TermPointer
}

var _ ent.Mutation = (*TermPointerMutation)(nil)

// termpointerOption allows management of the mutation configuration using functional options.
type termpointerOption func(*TermPointerMutation)

// newTermPointerMutation creates new mutation for the TermPointer entity.
func newTermPointerMutation(c config, op Op, opts ...termpointerOption) *TermPointerMutation {
	m := &TermPointerMutation{
		config:        c,
		op:            op,
		typ:           TypeTermPointer,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withTermPointerID sets the ID field of the mutation.
func withTermPointerID(id int) termpointerOption {
	return func(m *TermPointerMutation) {
		var (
			err   error
			once  sync.Once
			value *TermPointer
		)
		m.oldValue = func(ctx context.Context) (*TermPointer, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().TermPointer.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withTermPointer sets the old TermPointer of the mutation.
func withTermPointer(node *TermPointer) termpointerOption {
	return func(m *TermPointerMutation) {
		m.oldValue = func(context.Context) (*TermPointer, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m TermPointerMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m TermPointerMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *TermPointerMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *TermPointerMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().TermPointer.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetTermID sets the "term_id" field.
func (m *TermPointerMutation) SetTermID(i int) {
	m.term = &i
}

// TermID returns the value of the "term_id" field in the mutation.
func (m *TermPointerMutation) TermID() (r int, exists bool) {
	v := m.term
	if v == nil {
		return
	}
	return *v, true
}

// OldTermID returns the old "term_id" field's value of the TermPointer entity.
// If the TermPointer object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TermPointerMutation) OldTermID(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTermID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTermID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTermID: %w", err)
	}
	return oldValue.TermID, nil
}

// ClearTermID clears the value of the "term_id" field.
func (m *TermPointerMutation) ClearTermID() {
	m.term = nil
	m.clearedFields[termpointer.FieldTermID] = struct{}{}
}

// TermIDCleared returns if the "term_id" field was cleared in this mutation.
func (m *TermPointerMutation) TermIDCleared() bool {
	_, ok := m.clearedFields[termpointer.FieldTermID]
	return ok
}

// ResetTermID resets all changes to the "term_id" field.
func (m *TermPointerMutation) ResetTermID() {
	m.term = nil
	delete(m.clearedFields, termpointer.FieldTermID)
}

// SetRevisionID sets the "revision_id" field.
func (m *TermPointerMutation) SetRevisionID(i int) {
	m.revision = &i
}

// RevisionID returns the value of the "revision_id" field in the mutation.
func (m *TermPointerMutation) RevisionID() (r int, exists bool) {
	v := m.revision
	if v == nil {
		return
	}
	return *v, true
}

// OldRevisionID returns the old "revision_id" field's value of the TermPointer entity.
// If the TermPointer object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TermPointerMutation) OldRevisionID(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRevisionID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRevisionID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRevisionID: %w", err)
	}
	return oldValue.RevisionID, nil
}

// ClearRevisionID clears the value of the "revision_id" field.
func (m *TermPointerMutation) ClearRevisionID() {
	m.revision = nil
	m.clearedFields[termpointer.FieldRevisionID] = struct{}{}
}

// RevisionIDCleared returns if the "revision_id" field was cleared in this mutation.
func (m *TermPointerMutation) RevisionIDCleared() bool {
	_, ok := m.clearedFields[termpointer.FieldRevisionID]
	return ok
}

// ResetRevisionID resets all changes to the "revision_id" field.
func (m *TermPointerMutation) ResetRevisionID() {
	m.revision = nil
	delete(m.clearedFields, termpointer.FieldRevisionID)
}

// ClearTerm clears the "term" edge to the Term entity.
func (m *TermPointerMutation) ClearTerm() {
	m.clearedterm = true
}

// TermCleared reports if the "term" edge to the Term entity was cleared.
func (m *TermPointerMutation) TermCleared() bool {
	return m.TermIDCleared() || m.clearedterm
}

// TermIDs returns the "term" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// TermID instead. It exists only for internal usage by the builders.
func (m *TermPointerMutation) TermIDs() (ids []int) {
	if id := m.term; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetTerm resets all changes to the "term" edge.
func (m *TermPointerMutation) ResetTerm() {
	m.term = nil
	m.clearedterm = false
}

// ClearRevision clears the "revision" edge to the TermRevision entity.
func (m *TermPointerMutation) ClearRevision() {
	m.clearedrevision = true
}

// RevisionCleared reports if the "revision" edge to the TermRevision entity was cleared.
func (m *TermPointerMutation) RevisionCleared() bool {
	return m.RevisionIDCleared() || m.clearedrevision
}

// RevisionIDs returns the "revision" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// RevisionID instead. It exists only for internal usage by the builders.
func (m *TermPointerMutation) RevisionIDs() (ids []int) {
	if id := m.revision; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetRevision resets all changes to the "revision" edge.
func (m *TermPointerMutation) ResetRevision() {
	m.revision = nil
	m.clearedrevision = false
}

// Where appends a list predicates to the TermPointerMutation builder.
func (m *TermPointerMutation) Where(ps ...predicate.TermPointer) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *TermPointerMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (TermPointer).
func (m *TermPointerMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *TermPointerMutation) Fields() []string {
	fields := make([]string, 0, 2)
	if m.term != nil {
		fields = append(fields, termpointer.FieldTermID)
	}
	if m.revision != nil {
		fields = append(fields, termpointer.FieldRevisionID)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *TermPointerMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case termpointer.FieldTermID:
		return m.TermID()
	case termpointer.FieldRevisionID:
		return m.RevisionID()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *TermPointerMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case termpointer.FieldTermID:
		return m.OldTermID(ctx)
	case termpointer.FieldRevisionID:
		return m.OldRevisionID(ctx)
	}
	return nil, fmt.Errorf("unknown TermPointer field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TermPointerMutation) SetField(name string, value ent.Value) error {
	switch name {
	case termpointer.FieldTermID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTermID(v)
		return nil
	case termpointer.FieldRevisionID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRevisionID(v)
		return nil
	}
	return fmt.Errorf("unknown TermPointer field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *TermPointerMutation) AddedFields() []string {
	var fields []string
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *TermPointerMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TermPointerMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown TermPointer numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *TermPointerMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(termpointer.FieldTermID) {
		fields = append(fields, termpointer.FieldTermID)
	}
	if m.FieldCleared(termpointer.FieldRevisionID) {
		fields = append(fields, termpointer.FieldRevisionID)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *TermPointerMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *TermPointerMutation) ClearField(name string) error {
	switch name {
	case termpointer.FieldTermID:
		m.ClearTermID()
		return nil
	case termpointer.FieldRevisionID:
		m.ClearRevisionID()
		return nil
	}
	return fmt.Errorf("unknown TermPointer nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *TermPointerMutation) ResetField(name string) error {
	switch name {
	case termpointer.FieldTermID:
		m.ResetTermID()
		return nil
	case termpointer.FieldRevisionID:
		m.ResetRevisionID()
		return nil
	}
	return fmt.Errorf("unknown TermPointer field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *TermPointerMutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.term != nil {
		edges = append(edges, termpointer.EdgeTerm)
	}
	if m.revision != nil {
		edges = append(edges, termpointer.EdgeRevision)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *TermPointerMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case termpointer.EdgeTerm:
		if id := m.term; id != nil {
			return []ent.Value{*id}
		}
	case termpointer.EdgeRevision:
		if id := m.revision; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *TermPointerMutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *TermPointerMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *TermPointerMutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.clearedterm {
		edges = append(edges, termpointer.EdgeTerm)
	}
	if m.clearedrevision {
		edges = append(edges, termpointer.EdgeRevision)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *TermPointerMutation) EdgeCleared(name string) bool {
	switch name {
	case termpointer.EdgeTerm:
		return m.clearedterm
	case termpointer.EdgeRevision:
		return m.clearedrevision
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *TermPointerMutation) ClearEdge(name string) error {
	switch name {
	case termpointer.EdgeTerm:
		m.ClearTerm()
		return nil
	case termpointer.EdgeRevision:
		m.ClearRevision()
		return nil
	}
	return fmt.Errorf("unknown TermPointer unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *TermPointerMutation) ResetEdge(name string) error {
	switch name {
	case termpointer.EdgeTerm:
		m.ResetTerm()
		return nil
	case termpointer.EdgeRevision:
		m.ResetRevision()
		return nil
	}
	return fmt.Errorf("unknown TermPointer edge %s", name)
}

// TermRelatedMutation represents an operation that mutates the TermRelated nodes in the graph.
type TermRelatedMutation struct {
	config
	op             Op
	typ            string
	id             *int
	clearedFields  map[string]struct{}
	subject        *int
	clearedsubject bool
	related        *int
	clearedrelated bool
	done           bool
	oldValue       func(context.Context) (*TermRelated, error)
	predicates     []predicate.TermRelated
}

var _ ent.Mutation = (*TermRelatedMutation)(nil)

// termrelatedOption allows management of the mutation configuration using functional options.
type termrelatedOption func(*TermRelatedMutation)

// newTermRelatedMutation creates new mutation for the TermRelated entity.
func newTermRelatedMutation(c config, op Op, opts ...termrelatedOption) *TermRelatedMutation {
	m := &TermRelatedMutation{
		config:        c,
		op:            op,
		typ:           TypeTermRelated,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withTermRelatedID sets the ID field of the mutation.
func withTermRelatedID(id int) termrelatedOption {
	return func(m *TermRelatedMutation) {
		var (
			err   error
			once  sync.Once
			value *TermRelated
		)
		m.oldValue = func(ctx context.Context) (*TermRelated, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().TermRelated.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withTermRelated sets the old TermRelated of the mutation.
func withTermRelated(node *TermRelated) termrelatedOption {
	return func(m *TermRelatedMutation) {
		m.oldValue = func(context.Context) (*TermRelated, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m TermRelatedMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m TermRelatedMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *TermRelatedMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *TermRelatedMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().TermRelated.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetSubjectID sets the "subject" edge to the Term entity by id.
func (m *TermRelatedMutation) SetSubjectID(id int) {
	m.subject = &id
}

// ClearSubject clears the "subject" edge to the Term entity.
func (m *TermRelatedMutation) ClearSubject() {
	m.clearedsubject = true
}

// SubjectCleared reports if the "subject" edge to the Term entity was cleared.
func (m *TermRelatedMutation) SubjectCleared() bool {
	return m.clearedsubject
}

// SubjectID returns the "subject" edge ID in the mutation.
func (m *TermRelatedMutation) SubjectID() (id int, exists bool) {
	if m.subject != nil {
		return *m.subject, true
	}
	return
}

// SubjectIDs returns the "subject" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// SubjectID instead. It exists only for internal usage by the builders.
func (m *TermRelatedMutation) SubjectIDs() (ids []int) {
	if id := m.subject; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetSubject resets all changes to the "subject" edge.
func (m *TermRelatedMutation) ResetSubject() {
	m.subject = nil
	m.clearedsubject = false
}

// SetRelatedID sets the "related" edge to the Term entity by id.
func (m *TermRelatedMutation) SetRelatedID(id int) {
	m.related = &id
}

// ClearRelated clears the "related" edge to the Term entity.
func (m *TermRelatedMutation) ClearRelated() {
	m.clearedrelated = true
}

// RelatedCleared reports if the "related" edge to the Term entity was cleared.
func (m *TermRelatedMutation) RelatedCleared() bool {
	return m.clearedrelated
}

// RelatedID returns the "related" edge ID in the mutation.
func (m *TermRelatedMutation) RelatedID() (id int, exists bool) {
	if m.related != nil {
		return *m.related, true
	}
	return
}

// RelatedIDs returns the "related" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// RelatedID instead. It exists only for internal usage by the builders.
func (m *TermRelatedMutation) RelatedIDs() (ids []int) {
	if id := m.related; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetRelated resets all changes to the "related" edge.
func (m *TermRelatedMutation) ResetRelated() {
	m.related = nil
	m.clearedrelated = false
}

// Where appends a list predicates to the TermRelatedMutation builder.
func (m *TermRelatedMutation) Where(ps ...predicate.TermRelated) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *TermRelatedMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (TermRelated).
func (m *TermRelatedMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *TermRelatedMutation) Fields() []string {
	fields := make([]string, 0, 0)
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *TermRelatedMutation) Field(name string) (ent.Value, bool) {
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *TermRelatedMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	return nil, fmt.Errorf("unknown TermRelated field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TermRelatedMutation) SetField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown TermRelated field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *TermRelatedMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *TermRelatedMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TermRelatedMutation) AddField(name string, value ent.Value) error {
	return fmt.Errorf("unknown TermRelated numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *TermRelatedMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *TermRelatedMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *TermRelatedMutation) ClearField(name string) error {
	return fmt.Errorf("unknown TermRelated nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *TermRelatedMutation) ResetField(name string) error {
	return fmt.Errorf("unknown TermRelated field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *TermRelatedMutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.subject != nil {
		edges = append(edges, termrelated.EdgeSubject)
	}
	if m.related != nil {
		edges = append(edges, termrelated.EdgeRelated)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *TermRelatedMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case termrelated.EdgeSubject:
		if id := m.subject; id != nil {
			return []ent.Value{*id}
		}
	case termrelated.EdgeRelated:
		if id := m.related; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *TermRelatedMutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *TermRelatedMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *TermRelatedMutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.clearedsubject {
		edges = append(edges, termrelated.EdgeSubject)
	}
	if m.clearedrelated {
		edges = append(edges, termrelated.EdgeRelated)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *TermRelatedMutation) EdgeCleared(name string) bool {
	switch name {
	case termrelated.EdgeSubject:
		return m.clearedsubject
	case termrelated.EdgeRelated:
		return m.clearedrelated
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *TermRelatedMutation) ClearEdge(name string) error {
	switch name {
	case termrelated.EdgeSubject:
		m.ClearSubject()
		return nil
	case termrelated.EdgeRelated:
		m.ClearRelated()
		return nil
	}
	return fmt.Errorf("unknown TermRelated unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *TermRelatedMutation) ResetEdge(name string) error {
	switch name {
	case termrelated.EdgeSubject:
		m.ResetSubject()
		return nil
	case termrelated.EdgeRelated:
		m.ResetRelated()
		return nil
	}
	return fmt.Errorf("unknown TermRelated edge %s", name)
}

// TermRevisionMutation represents an operation that mutates the TermRevision nodes in the graph.
type TermRevisionMutation struct {
	config
	op              Op
	typ             string
	id              *int
	description     *string
	created_at      *time.Time
	updated_at      *time.Time
	clearedFields   map[string]struct{}
	pointers        map[int]struct{}
	removedpointers map[int]struct{}
	clearedpointers bool
	term            *int
	clearedterm     bool
	done            bool
	oldValue        func(context.Context) (*TermRevision, error)
	predicates      []predicate.TermRevision
}

var _ ent.Mutation = (*TermRevisionMutation)(nil)

// termrevisionOption allows management of the mutation configuration using functional options.
type termrevisionOption func(*TermRevisionMutation)

// newTermRevisionMutation creates new mutation for the TermRevision entity.
func newTermRevisionMutation(c config, op Op, opts ...termrevisionOption) *TermRevisionMutation {
	m := &TermRevisionMutation{
		config:        c,
		op:            op,
		typ:           TypeTermRevision,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withTermRevisionID sets the ID field of the mutation.
func withTermRevisionID(id int) termrevisionOption {
	return func(m *TermRevisionMutation) {
		var (
			err   error
			once  sync.Once
			value *TermRevision
		)
		m.oldValue = func(ctx context.Context) (*TermRevision, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().TermRevision.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withTermRevision sets the old TermRevision of the mutation.
func withTermRevision(node *TermRevision) termrevisionOption {
	return func(m *TermRevisionMutation) {
		m.oldValue = func(context.Context) (*TermRevision, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m TermRevisionMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m TermRevisionMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *TermRevisionMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *TermRevisionMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().TermRevision.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetDescription sets the "description" field.
func (m *TermRevisionMutation) SetDescription(s string) {
	m.description = &s
}

// Description returns the value of the "description" field in the mutation.
func (m *TermRevisionMutation) Description() (r string, exists bool) {
	v := m.description
	if v == nil {
		return
	}
	return *v, true
}

// OldDescription returns the old "description" field's value of the TermRevision entity.
// If the TermRevision object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TermRevisionMutation) OldDescription(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDescription is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDescription requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDescription: %w", err)
	}
	return oldValue.Description, nil
}

// ClearDescription clears the value of the "description" field.
func (m *TermRevisionMutation) ClearDescription() {
	m.description = nil
	m.clearedFields[termrevision.FieldDescription] = struct{}{}
}

// DescriptionCleared returns if the "description" field was cleared in this mutation.
func (m *TermRevisionMutation) DescriptionCleared() bool {
	_, ok := m.clearedFields[termrevision.FieldDescription]
	return ok
}

// ResetDescription resets all changes to the "description" field.
func (m *TermRevisionMutation) ResetDescription() {
	m.description = nil
	delete(m.clearedFields, termrevision.FieldDescription)
}

// SetTermID sets the "term_id" field.
func (m *TermRevisionMutation) SetTermID(i int) {
	m.term = &i
}

// TermID returns the value of the "term_id" field in the mutation.
func (m *TermRevisionMutation) TermID() (r int, exists bool) {
	v := m.term
	if v == nil {
		return
	}
	return *v, true
}

// OldTermID returns the old "term_id" field's value of the TermRevision entity.
// If the TermRevision object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TermRevisionMutation) OldTermID(ctx context.Context) (v int, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTermID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTermID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTermID: %w", err)
	}
	return oldValue.TermID, nil
}

// ClearTermID clears the value of the "term_id" field.
func (m *TermRevisionMutation) ClearTermID() {
	m.term = nil
	m.clearedFields[termrevision.FieldTermID] = struct{}{}
}

// TermIDCleared returns if the "term_id" field was cleared in this mutation.
func (m *TermRevisionMutation) TermIDCleared() bool {
	_, ok := m.clearedFields[termrevision.FieldTermID]
	return ok
}

// ResetTermID resets all changes to the "term_id" field.
func (m *TermRevisionMutation) ResetTermID() {
	m.term = nil
	delete(m.clearedFields, termrevision.FieldTermID)
}

// SetCreatedAt sets the "created_at" field.
func (m *TermRevisionMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *TermRevisionMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the TermRevision entity.
// If the TermRevision object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TermRevisionMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *TermRevisionMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *TermRevisionMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *TermRevisionMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the TermRevision entity.
// If the TermRevision object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *TermRevisionMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *TermRevisionMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// AddPointerIDs adds the "pointers" edge to the TermPointer entity by ids.
func (m *TermRevisionMutation) AddPointerIDs(ids ...int) {
	if m.pointers == nil {
		m.pointers = make(map[int]struct{})
	}
	for i := range ids {
		m.pointers[ids[i]] = struct{}{}
	}
}

// ClearPointers clears the "pointers" edge to the TermPointer entity.
func (m *TermRevisionMutation) ClearPointers() {
	m.clearedpointers = true
}

// PointersCleared reports if the "pointers" edge to the TermPointer entity was cleared.
func (m *TermRevisionMutation) PointersCleared() bool {
	return m.clearedpointers
}

// RemovePointerIDs removes the "pointers" edge to the TermPointer entity by IDs.
func (m *TermRevisionMutation) RemovePointerIDs(ids ...int) {
	if m.removedpointers == nil {
		m.removedpointers = make(map[int]struct{})
	}
	for i := range ids {
		delete(m.pointers, ids[i])
		m.removedpointers[ids[i]] = struct{}{}
	}
}

// RemovedPointers returns the removed IDs of the "pointers" edge to the TermPointer entity.
func (m *TermRevisionMutation) RemovedPointersIDs() (ids []int) {
	for id := range m.removedpointers {
		ids = append(ids, id)
	}
	return
}

// PointersIDs returns the "pointers" edge IDs in the mutation.
func (m *TermRevisionMutation) PointersIDs() (ids []int) {
	for id := range m.pointers {
		ids = append(ids, id)
	}
	return
}

// ResetPointers resets all changes to the "pointers" edge.
func (m *TermRevisionMutation) ResetPointers() {
	m.pointers = nil
	m.clearedpointers = false
	m.removedpointers = nil
}

// ClearTerm clears the "term" edge to the Term entity.
func (m *TermRevisionMutation) ClearTerm() {
	m.clearedterm = true
}

// TermCleared reports if the "term" edge to the Term entity was cleared.
func (m *TermRevisionMutation) TermCleared() bool {
	return m.TermIDCleared() || m.clearedterm
}

// TermIDs returns the "term" edge IDs in the mutation.
// Note that IDs always returns len(IDs) <= 1 for unique edges, and you should use
// TermID instead. It exists only for internal usage by the builders.
func (m *TermRevisionMutation) TermIDs() (ids []int) {
	if id := m.term; id != nil {
		ids = append(ids, *id)
	}
	return
}

// ResetTerm resets all changes to the "term" edge.
func (m *TermRevisionMutation) ResetTerm() {
	m.term = nil
	m.clearedterm = false
}

// Where appends a list predicates to the TermRevisionMutation builder.
func (m *TermRevisionMutation) Where(ps ...predicate.TermRevision) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *TermRevisionMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (TermRevision).
func (m *TermRevisionMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *TermRevisionMutation) Fields() []string {
	fields := make([]string, 0, 4)
	if m.description != nil {
		fields = append(fields, termrevision.FieldDescription)
	}
	if m.term != nil {
		fields = append(fields, termrevision.FieldTermID)
	}
	if m.created_at != nil {
		fields = append(fields, termrevision.FieldCreatedAt)
	}
	if m.updated_at != nil {
		fields = append(fields, termrevision.FieldUpdatedAt)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *TermRevisionMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case termrevision.FieldDescription:
		return m.Description()
	case termrevision.FieldTermID:
		return m.TermID()
	case termrevision.FieldCreatedAt:
		return m.CreatedAt()
	case termrevision.FieldUpdatedAt:
		return m.UpdatedAt()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *TermRevisionMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case termrevision.FieldDescription:
		return m.OldDescription(ctx)
	case termrevision.FieldTermID:
		return m.OldTermID(ctx)
	case termrevision.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case termrevision.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	}
	return nil, fmt.Errorf("unknown TermRevision field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TermRevisionMutation) SetField(name string, value ent.Value) error {
	switch name {
	case termrevision.FieldDescription:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDescription(v)
		return nil
	case termrevision.FieldTermID:
		v, ok := value.(int)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTermID(v)
		return nil
	case termrevision.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case termrevision.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	}
	return fmt.Errorf("unknown TermRevision field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *TermRevisionMutation) AddedFields() []string {
	var fields []string
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *TermRevisionMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *TermRevisionMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown TermRevision numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *TermRevisionMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(termrevision.FieldDescription) {
		fields = append(fields, termrevision.FieldDescription)
	}
	if m.FieldCleared(termrevision.FieldTermID) {
		fields = append(fields, termrevision.FieldTermID)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *TermRevisionMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *TermRevisionMutation) ClearField(name string) error {
	switch name {
	case termrevision.FieldDescription:
		m.ClearDescription()
		return nil
	case termrevision.FieldTermID:
		m.ClearTermID()
		return nil
	}
	return fmt.Errorf("unknown TermRevision nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *TermRevisionMutation) ResetField(name string) error {
	switch name {
	case termrevision.FieldDescription:
		m.ResetDescription()
		return nil
	case termrevision.FieldTermID:
		m.ResetTermID()
		return nil
	case termrevision.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case termrevision.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	}
	return fmt.Errorf("unknown TermRevision field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *TermRevisionMutation) AddedEdges() []string {
	edges := make([]string, 0, 2)
	if m.pointers != nil {
		edges = append(edges, termrevision.EdgePointers)
	}
	if m.term != nil {
		edges = append(edges, termrevision.EdgeTerm)
	}
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *TermRevisionMutation) AddedIDs(name string) []ent.Value {
	switch name {
	case termrevision.EdgePointers:
		ids := make([]ent.Value, 0, len(m.pointers))
		for id := range m.pointers {
			ids = append(ids, id)
		}
		return ids
	case termrevision.EdgeTerm:
		if id := m.term; id != nil {
			return []ent.Value{*id}
		}
	}
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *TermRevisionMutation) RemovedEdges() []string {
	edges := make([]string, 0, 2)
	if m.removedpointers != nil {
		edges = append(edges, termrevision.EdgePointers)
	}
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *TermRevisionMutation) RemovedIDs(name string) []ent.Value {
	switch name {
	case termrevision.EdgePointers:
		ids := make([]ent.Value, 0, len(m.removedpointers))
		for id := range m.removedpointers {
			ids = append(ids, id)
		}
		return ids
	}
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *TermRevisionMutation) ClearedEdges() []string {
	edges := make([]string, 0, 2)
	if m.clearedpointers {
		edges = append(edges, termrevision.EdgePointers)
	}
	if m.clearedterm {
		edges = append(edges, termrevision.EdgeTerm)
	}
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *TermRevisionMutation) EdgeCleared(name string) bool {
	switch name {
	case termrevision.EdgePointers:
		return m.clearedpointers
	case termrevision.EdgeTerm:
		return m.clearedterm
	}
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *TermRevisionMutation) ClearEdge(name string) error {
	switch name {
	case termrevision.EdgeTerm:
		m.ClearTerm()
		return nil
	}
	return fmt.Errorf("unknown TermRevision unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *TermRevisionMutation) ResetEdge(name string) error {
	switch name {
	case termrevision.EdgePointers:
		m.ResetPointers()
		return nil
	case termrevision.EdgeTerm:
		m.ResetTerm()
		return nil
	}
	return fmt.Errorf("unknown TermRevision edge %s", name)
}
