// Code generated by ent, DO NOT EDIT.

package ent

import (
	"devwiki/ent/schema"
	"devwiki/ent/term"
	"devwiki/ent/termrevision"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	termFields := schema.Term{}.Fields()
	_ = termFields
	// termDescCreatedAt is the schema descriptor for created_at field.
	termDescCreatedAt := termFields[1].Descriptor()
	// term.DefaultCreatedAt holds the default value on creation for the created_at field.
	term.DefaultCreatedAt = termDescCreatedAt.Default.(func() time.Time)
	// termDescUpdatedAt is the schema descriptor for updated_at field.
	termDescUpdatedAt := termFields[2].Descriptor()
	// term.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	term.DefaultUpdatedAt = termDescUpdatedAt.Default.(func() time.Time)
	// term.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	term.UpdateDefaultUpdatedAt = termDescUpdatedAt.UpdateDefault.(func() time.Time)
	termrevisionFields := schema.TermRevision{}.Fields()
	_ = termrevisionFields
	// termrevisionDescCreatedAt is the schema descriptor for created_at field.
	termrevisionDescCreatedAt := termrevisionFields[2].Descriptor()
	// termrevision.DefaultCreatedAt holds the default value on creation for the created_at field.
	termrevision.DefaultCreatedAt = termrevisionDescCreatedAt.Default.(func() time.Time)
	// termrevisionDescUpdatedAt is the schema descriptor for updated_at field.
	termrevisionDescUpdatedAt := termrevisionFields[3].Descriptor()
	// termrevision.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	termrevision.DefaultUpdatedAt = termrevisionDescUpdatedAt.Default.(func() time.Time)
	// termrevision.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	termrevision.UpdateDefaultUpdatedAt = termrevisionDescUpdatedAt.UpdateDefault.(func() time.Time)
}
