// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"devwiki/ent/predicate"
	"devwiki/ent/term"
	"devwiki/ent/termpointer"
	"devwiki/ent/termrelated"
	"devwiki/ent/termrevision"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TermQuery is the builder for querying Term entities.
type TermQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.Term
	// eager-loading edges.
	withRevisions *TermRevisionQuery
	withPointers  *TermPointerQuery
	withSubjectID *TermRelatedQuery
	withRelatedID *TermRelatedQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TermQuery builder.
func (tq *TermQuery) Where(ps ...predicate.Term) *TermQuery {
	tq.predicates = append(tq.predicates, ps...)
	return tq
}

// Limit adds a limit step to the query.
func (tq *TermQuery) Limit(limit int) *TermQuery {
	tq.limit = &limit
	return tq
}

// Offset adds an offset step to the query.
func (tq *TermQuery) Offset(offset int) *TermQuery {
	tq.offset = &offset
	return tq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tq *TermQuery) Unique(unique bool) *TermQuery {
	tq.unique = &unique
	return tq
}

// Order adds an order step to the query.
func (tq *TermQuery) Order(o ...OrderFunc) *TermQuery {
	tq.order = append(tq.order, o...)
	return tq
}

// QueryRevisions chains the current query on the "revisions" edge.
func (tq *TermQuery) QueryRevisions() *TermRevisionQuery {
	query := &TermRevisionQuery{config: tq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(term.Table, term.FieldID, selector),
			sqlgraph.To(termrevision.Table, termrevision.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, term.RevisionsTable, term.RevisionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(tq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPointers chains the current query on the "pointers" edge.
func (tq *TermQuery) QueryPointers() *TermPointerQuery {
	query := &TermPointerQuery{config: tq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(term.Table, term.FieldID, selector),
			sqlgraph.To(termpointer.Table, termpointer.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, term.PointersTable, term.PointersColumn),
		)
		fromU = sqlgraph.SetNeighbors(tq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySubjectID chains the current query on the "subject_id" edge.
func (tq *TermQuery) QuerySubjectID() *TermRelatedQuery {
	query := &TermRelatedQuery{config: tq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(term.Table, term.FieldID, selector),
			sqlgraph.To(termrelated.Table, termrelated.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, term.SubjectIDTable, term.SubjectIDColumn),
		)
		fromU = sqlgraph.SetNeighbors(tq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRelatedID chains the current query on the "related_id" edge.
func (tq *TermQuery) QueryRelatedID() *TermRelatedQuery {
	query := &TermRelatedQuery{config: tq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(term.Table, term.FieldID, selector),
			sqlgraph.To(termrelated.Table, termrelated.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, term.RelatedIDTable, term.RelatedIDColumn),
		)
		fromU = sqlgraph.SetNeighbors(tq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Term entity from the query.
// Returns a *NotFoundError when no Term was found.
func (tq *TermQuery) First(ctx context.Context) (*Term, error) {
	nodes, err := tq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{term.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tq *TermQuery) FirstX(ctx context.Context) *Term {
	node, err := tq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Term ID from the query.
// Returns a *NotFoundError when no Term ID was found.
func (tq *TermQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{term.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tq *TermQuery) FirstIDX(ctx context.Context) int {
	id, err := tq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Term entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Term entity is found.
// Returns a *NotFoundError when no Term entities are found.
func (tq *TermQuery) Only(ctx context.Context) (*Term, error) {
	nodes, err := tq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{term.Label}
	default:
		return nil, &NotSingularError{term.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tq *TermQuery) OnlyX(ctx context.Context) *Term {
	node, err := tq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Term ID in the query.
// Returns a *NotSingularError when more than one Term ID is found.
// Returns a *NotFoundError when no entities are found.
func (tq *TermQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{term.Label}
	default:
		err = &NotSingularError{term.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tq *TermQuery) OnlyIDX(ctx context.Context) int {
	id, err := tq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Terms.
func (tq *TermQuery) All(ctx context.Context) ([]*Term, error) {
	if err := tq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return tq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (tq *TermQuery) AllX(ctx context.Context) []*Term {
	nodes, err := tq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Term IDs.
func (tq *TermQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := tq.Select(term.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tq *TermQuery) IDsX(ctx context.Context) []int {
	ids, err := tq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tq *TermQuery) Count(ctx context.Context) (int, error) {
	if err := tq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return tq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (tq *TermQuery) CountX(ctx context.Context) int {
	count, err := tq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tq *TermQuery) Exist(ctx context.Context) (bool, error) {
	if err := tq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return tq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (tq *TermQuery) ExistX(ctx context.Context) bool {
	exist, err := tq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TermQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tq *TermQuery) Clone() *TermQuery {
	if tq == nil {
		return nil
	}
	return &TermQuery{
		config:        tq.config,
		limit:         tq.limit,
		offset:        tq.offset,
		order:         append([]OrderFunc{}, tq.order...),
		predicates:    append([]predicate.Term{}, tq.predicates...),
		withRevisions: tq.withRevisions.Clone(),
		withPointers:  tq.withPointers.Clone(),
		withSubjectID: tq.withSubjectID.Clone(),
		withRelatedID: tq.withRelatedID.Clone(),
		// clone intermediate query.
		sql:    tq.sql.Clone(),
		path:   tq.path,
		unique: tq.unique,
	}
}

// WithRevisions tells the query-builder to eager-load the nodes that are connected to
// the "revisions" edge. The optional arguments are used to configure the query builder of the edge.
func (tq *TermQuery) WithRevisions(opts ...func(*TermRevisionQuery)) *TermQuery {
	query := &TermRevisionQuery{config: tq.config}
	for _, opt := range opts {
		opt(query)
	}
	tq.withRevisions = query
	return tq
}

// WithPointers tells the query-builder to eager-load the nodes that are connected to
// the "pointers" edge. The optional arguments are used to configure the query builder of the edge.
func (tq *TermQuery) WithPointers(opts ...func(*TermPointerQuery)) *TermQuery {
	query := &TermPointerQuery{config: tq.config}
	for _, opt := range opts {
		opt(query)
	}
	tq.withPointers = query
	return tq
}

// WithSubjectID tells the query-builder to eager-load the nodes that are connected to
// the "subject_id" edge. The optional arguments are used to configure the query builder of the edge.
func (tq *TermQuery) WithSubjectID(opts ...func(*TermRelatedQuery)) *TermQuery {
	query := &TermRelatedQuery{config: tq.config}
	for _, opt := range opts {
		opt(query)
	}
	tq.withSubjectID = query
	return tq
}

// WithRelatedID tells the query-builder to eager-load the nodes that are connected to
// the "related_id" edge. The optional arguments are used to configure the query builder of the edge.
func (tq *TermQuery) WithRelatedID(opts ...func(*TermRelatedQuery)) *TermQuery {
	query := &TermRelatedQuery{config: tq.config}
	for _, opt := range opts {
		opt(query)
	}
	tq.withRelatedID = query
	return tq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Term.Query().
//		GroupBy(term.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (tq *TermQuery) GroupBy(field string, fields ...string) *TermGroupBy {
	grbuild := &TermGroupBy{config: tq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := tq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return tq.sqlQuery(ctx), nil
	}
	grbuild.label = term.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.Term.Query().
//		Select(term.FieldName).
//		Scan(ctx, &v)
//
func (tq *TermQuery) Select(fields ...string) *TermSelect {
	tq.fields = append(tq.fields, fields...)
	selbuild := &TermSelect{TermQuery: tq}
	selbuild.label = term.Label
	selbuild.flds, selbuild.scan = &tq.fields, selbuild.Scan
	return selbuild
}

func (tq *TermQuery) prepareQuery(ctx context.Context) error {
	for _, f := range tq.fields {
		if !term.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tq.path != nil {
		prev, err := tq.path(ctx)
		if err != nil {
			return err
		}
		tq.sql = prev
	}
	return nil
}

func (tq *TermQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Term, error) {
	var (
		nodes       = []*Term{}
		_spec       = tq.querySpec()
		loadedTypes = [4]bool{
			tq.withRevisions != nil,
			tq.withPointers != nil,
			tq.withSubjectID != nil,
			tq.withRelatedID != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*Term).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &Term{config: tq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := tq.withRevisions; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[int]*Term)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
			nodes[i].Edges.Revisions = []*TermRevision{}
		}
		query.Where(predicate.TermRevision(func(s *sql.Selector) {
			s.Where(sql.InValues(term.RevisionsColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.TermID
			node, ok := nodeids[fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "term_id" returned %v for node %v`, fk, n.ID)
			}
			node.Edges.Revisions = append(node.Edges.Revisions, n)
		}
	}

	if query := tq.withPointers; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[int]*Term)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
			nodes[i].Edges.Pointers = []*TermPointer{}
		}
		query.Where(predicate.TermPointer(func(s *sql.Selector) {
			s.Where(sql.InValues(term.PointersColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.TermID
			node, ok := nodeids[fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "term_id" returned %v for node %v`, fk, n.ID)
			}
			node.Edges.Pointers = append(node.Edges.Pointers, n)
		}
	}

	if query := tq.withSubjectID; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[int]*Term)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
			nodes[i].Edges.SubjectID = []*TermRelated{}
		}
		query.withFKs = true
		query.Where(predicate.TermRelated(func(s *sql.Selector) {
			s.Where(sql.InValues(term.SubjectIDColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.term_subject_id
			if fk == nil {
				return nil, fmt.Errorf(`foreign-key "term_subject_id" is nil for node %v`, n.ID)
			}
			node, ok := nodeids[*fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "term_subject_id" returned %v for node %v`, *fk, n.ID)
			}
			node.Edges.SubjectID = append(node.Edges.SubjectID, n)
		}
	}

	if query := tq.withRelatedID; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[int]*Term)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
			nodes[i].Edges.RelatedID = []*TermRelated{}
		}
		query.withFKs = true
		query.Where(predicate.TermRelated(func(s *sql.Selector) {
			s.Where(sql.InValues(term.RelatedIDColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.term_related_id
			if fk == nil {
				return nil, fmt.Errorf(`foreign-key "term_related_id" is nil for node %v`, n.ID)
			}
			node, ok := nodeids[*fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "term_related_id" returned %v for node %v`, *fk, n.ID)
			}
			node.Edges.RelatedID = append(node.Edges.RelatedID, n)
		}
	}

	return nodes, nil
}

func (tq *TermQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tq.querySpec()
	_spec.Node.Columns = tq.fields
	if len(tq.fields) > 0 {
		_spec.Unique = tq.unique != nil && *tq.unique
	}
	return sqlgraph.CountNodes(ctx, tq.driver, _spec)
}

func (tq *TermQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := tq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (tq *TermQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   term.Table,
			Columns: term.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: term.FieldID,
			},
		},
		From:   tq.sql,
		Unique: true,
	}
	if unique := tq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := tq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, term.FieldID)
		for i := range fields {
			if fields[i] != term.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tq *TermQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tq.driver.Dialect())
	t1 := builder.Table(term.Table)
	columns := tq.fields
	if len(columns) == 0 {
		columns = term.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tq.sql != nil {
		selector = tq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tq.unique != nil && *tq.unique {
		selector.Distinct()
	}
	for _, p := range tq.predicates {
		p(selector)
	}
	for _, p := range tq.order {
		p(selector)
	}
	if offset := tq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TermGroupBy is the group-by builder for Term entities.
type TermGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tgb *TermGroupBy) Aggregate(fns ...AggregateFunc) *TermGroupBy {
	tgb.fns = append(tgb.fns, fns...)
	return tgb
}

// Scan applies the group-by query and scans the result into the given value.
func (tgb *TermGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := tgb.path(ctx)
	if err != nil {
		return err
	}
	tgb.sql = query
	return tgb.sqlScan(ctx, v)
}

func (tgb *TermGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range tgb.fields {
		if !term.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := tgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (tgb *TermGroupBy) sqlQuery() *sql.Selector {
	selector := tgb.sql.Select()
	aggregation := make([]string, 0, len(tgb.fns))
	for _, fn := range tgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(tgb.fields)+len(tgb.fns))
		for _, f := range tgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(tgb.fields...)...)
}

// TermSelect is the builder for selecting fields of Term entities.
type TermSelect struct {
	*TermQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (ts *TermSelect) Scan(ctx context.Context, v interface{}) error {
	if err := ts.prepareQuery(ctx); err != nil {
		return err
	}
	ts.sql = ts.TermQuery.sqlQuery(ctx)
	return ts.sqlScan(ctx, v)
}

func (ts *TermSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := ts.sql.Query()
	if err := ts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
