// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"devwiki/ent/term"
	"devwiki/ent/termrevision"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TermRevisionCreate is the builder for creating a TermRevision entity.
type TermRevisionCreate struct {
	config
	mutation *TermRevisionMutation
	hooks    []Hook
}

// SetDescription sets the "description" field.
func (trc *TermRevisionCreate) SetDescription(s string) *TermRevisionCreate {
	trc.mutation.SetDescription(s)
	return trc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (trc *TermRevisionCreate) SetNillableDescription(s *string) *TermRevisionCreate {
	if s != nil {
		trc.SetDescription(*s)
	}
	return trc
}

// SetTermID sets the "term_id" field.
func (trc *TermRevisionCreate) SetTermID(i int) *TermRevisionCreate {
	trc.mutation.SetTermID(i)
	return trc
}

// SetNillableTermID sets the "term_id" field if the given value is not nil.
func (trc *TermRevisionCreate) SetNillableTermID(i *int) *TermRevisionCreate {
	if i != nil {
		trc.SetTermID(*i)
	}
	return trc
}

// SetCreatedAt sets the "created_at" field.
func (trc *TermRevisionCreate) SetCreatedAt(t time.Time) *TermRevisionCreate {
	trc.mutation.SetCreatedAt(t)
	return trc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (trc *TermRevisionCreate) SetNillableCreatedAt(t *time.Time) *TermRevisionCreate {
	if t != nil {
		trc.SetCreatedAt(*t)
	}
	return trc
}

// SetUpdatedAt sets the "updated_at" field.
func (trc *TermRevisionCreate) SetUpdatedAt(t time.Time) *TermRevisionCreate {
	trc.mutation.SetUpdatedAt(t)
	return trc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (trc *TermRevisionCreate) SetNillableUpdatedAt(t *time.Time) *TermRevisionCreate {
	if t != nil {
		trc.SetUpdatedAt(*t)
	}
	return trc
}

// SetTerm sets the "term" edge to the Term entity.
func (trc *TermRevisionCreate) SetTerm(t *Term) *TermRevisionCreate {
	return trc.SetTermID(t.ID)
}

// Mutation returns the TermRevisionMutation object of the builder.
func (trc *TermRevisionCreate) Mutation() *TermRevisionMutation {
	return trc.mutation
}

// Save creates the TermRevision in the database.
func (trc *TermRevisionCreate) Save(ctx context.Context) (*TermRevision, error) {
	var (
		err  error
		node *TermRevision
	)
	trc.defaults()
	if len(trc.hooks) == 0 {
		if err = trc.check(); err != nil {
			return nil, err
		}
		node, err = trc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TermRevisionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = trc.check(); err != nil {
				return nil, err
			}
			trc.mutation = mutation
			if node, err = trc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(trc.hooks) - 1; i >= 0; i-- {
			if trc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = trc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, trc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*TermRevision)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from TermRevisionMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (trc *TermRevisionCreate) SaveX(ctx context.Context) *TermRevision {
	v, err := trc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (trc *TermRevisionCreate) Exec(ctx context.Context) error {
	_, err := trc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (trc *TermRevisionCreate) ExecX(ctx context.Context) {
	if err := trc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (trc *TermRevisionCreate) defaults() {
	if _, ok := trc.mutation.CreatedAt(); !ok {
		v := termrevision.DefaultCreatedAt()
		trc.mutation.SetCreatedAt(v)
	}
	if _, ok := trc.mutation.UpdatedAt(); !ok {
		v := termrevision.DefaultUpdatedAt()
		trc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (trc *TermRevisionCreate) check() error {
	if _, ok := trc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TermRevision.created_at"`)}
	}
	if _, ok := trc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "TermRevision.updated_at"`)}
	}
	return nil
}

func (trc *TermRevisionCreate) sqlSave(ctx context.Context) (*TermRevision, error) {
	_node, _spec := trc.createSpec()
	if err := sqlgraph.CreateNode(ctx, trc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (trc *TermRevisionCreate) createSpec() (*TermRevision, *sqlgraph.CreateSpec) {
	var (
		_node = &TermRevision{config: trc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: termrevision.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: termrevision.FieldID,
			},
		}
	)
	if value, ok := trc.mutation.Description(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: termrevision.FieldDescription,
		})
		_node.Description = value
	}
	if value, ok := trc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: termrevision.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := trc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: termrevision.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if nodes := trc.mutation.TermIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   termrevision.TermTable,
			Columns: []string{termrevision.TermColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: term.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TermID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TermRevisionCreateBulk is the builder for creating many TermRevision entities in bulk.
type TermRevisionCreateBulk struct {
	config
	builders []*TermRevisionCreate
}

// Save creates the TermRevision entities in the database.
func (trcb *TermRevisionCreateBulk) Save(ctx context.Context) ([]*TermRevision, error) {
	specs := make([]*sqlgraph.CreateSpec, len(trcb.builders))
	nodes := make([]*TermRevision, len(trcb.builders))
	mutators := make([]Mutator, len(trcb.builders))
	for i := range trcb.builders {
		func(i int, root context.Context) {
			builder := trcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TermRevisionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, trcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, trcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, trcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (trcb *TermRevisionCreateBulk) SaveX(ctx context.Context) []*TermRevision {
	v, err := trcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (trcb *TermRevisionCreateBulk) Exec(ctx context.Context) error {
	_, err := trcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (trcb *TermRevisionCreateBulk) ExecX(ctx context.Context) {
	if err := trcb.Exec(ctx); err != nil {
		panic(err)
	}
}
