// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Term is the predicate function for term builders.
type Term func(*sql.Selector)

// TermPointer is the predicate function for termpointer builders.
type TermPointer func(*sql.Selector)

// TermRelated is the predicate function for termrelated builders.
type TermRelated func(*sql.Selector)

// TermRevision is the predicate function for termrevision builders.
type TermRevision func(*sql.Selector)
